### ISSUE TITLE
Migração para o QGIS 3.0

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#174]
Em Abril de 2018 está previsto o lançamento da versão LTR do QGIS, a versão 3.2 . Uma série de mudanças e melhorias que foram implementadas na nova versão do QGIS, versão esta que atualmente está em release candidate (DEZ 17). Para executar a migração do DSGTools para o novo QGIS, os seguintes passos deverão ser seguidos:

- [x] Conversão do código do Python2 para o Python3;
- [x] Migração da QT4 para a QT5;
- [x] Reorganização do código do DSGTools;
- [x] Ajustar promoted widgets segundo a nova estrutura;
- [x] Criação dos gerenciadores de interface;
- [x] Migração das Ferramentas de Produção;
- [x] Migração das Ferramentas de Carregamento de Camadas;
- [x] Migração das Ferramentas de Criação de Banco de Dados;
- [x] Migração das Ferramentas de Gerência de Banco de Dados;
- [x] Migração da Ferramenta de Conversão de banco de dados;
- [x] Migração das demais ferramentas (misc)

**Comment by rsmaior** [comment]
Conforme a mailing list dev do QGIS https://lists.osgeo.org/pipermail/qgis-developer/2018-January/051322.html está sendo criada uma página com orientações gerais para migração de plugins. Talvez seja interessante dar uma olhada. 

Link da página: https://github.com/qgis/QGIS/wiki/Plugin-migration-to-QGIS-3
