### ISSUE TITLE
Refatoração da Configuração da Cobertura Terrestre

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#187]
A configuração atual de cobertura terrestre não está de acordo com o novo paradigma do DSGTools de ser genérico (bancos com modelagens diferentes da nativa do DSGTools, com colunas geométricas distintas da implementação supracitada). Esse fato é um problema, pois para fazer a desconstrução de área do issue #95 , deve existir uma forma transparente de relacionar camadas de centroide com as respectivas áreas.

Passos do refectory:
- [ ] Definir o novo formato do json de configuração;
- [ ] Refazer o SetupEarthCoverage (passar a usar a coluna geométrica na configuração);
- [ ] Refazer o arquivo de configuração da cobertura terrestre;
- [ ] Refazer a criação da estrutura de cobertura terrestre (mudar para tabelas separadas, ao invés de coluna geométrica a mais);
- [ ] Refazer o fechamento de áreas da cobertura terrestre.

**Comment by phborba** [comment]
Sem relevância, dado que o uso de processing, models e workflow suprime o armazenamento em banco de configuração.
