### ISSUE TITLE
Migração do Carrega para o Processing

### ISSUE THREAD

**Issue by phborba** [dsgoficial/DsgTools#387]
Para facilitar a integração com o SAP, o carrega camadas será migrado para o processing. Serão criados os seguintes processos que podem ser encadeados:

- [x] Carregar camada
- [x] Mapear domínios
- [x] Atribuir estilos
- [x] Atribuir filtro espacial (nova funcionalidade)
- [x] Organizar camadas por critérios (ponto, linha e área, por exemplo)
- [x] Executar join
- [ ] Construir multivalorado
- [ ] Atribuir formulário e código python custom
- [x] Atribuir alias de nome e atributo (nova funcionalidade)
- [x] Atribuir regra de pintar formulário (nova funcionalidade)
- [x] Adicionar coluna de medida

**Comment by dinizime** [comment]
O requisito " Atribuir formulário e código python custom" não é mais necessário.

O requisito " Construir multivalorado" não é mais necessário no momento pois a EDGV 3.0 foi implementada sem multivalorados
